In [20]:
import numpy as np
a = np.array([[1,9,3], [5,6,13], [9,10,11]])
w,v = np.linalg.eig(a)
print(w, '\n', v)

[ 23.8397550+0.j          -2.9198775+3.41945083j  -2.9198775-3.41945083j] 
 [[ 0.33587680+0.j          0.76985789+0.j          0.76985789-0.j        ]
 [ 0.61439170+0.j         -0.26029357+0.40882556j -0.26029357-0.40882556j]
 [ 0.71393950+0.j         -0.22503551-0.34897961j -0.22503551+0.34897961j]]


In [39]:
import numpy as np
import numpy.linalg as linalg

A = np.random.random((3,3))
eigenValues, eigenVectors = linalg.eig(A)

idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
#eigenValues=eigenValues[0:2]
#eigenVectors=eigenVectors[:,0:2]
#eigenVectors = np.reshape(eigenVectors, (K,D))
print(eigenValues, '\n', eigenVectors)

list_feature = []
for i in np.arange(3):
    X_features = []
    X_pca = X_all[:,:,:,i]
    for n in range(len(X_all)):
        img = X_pca[n]
        feature = np.dot(list_eigen_vectors[i], np.reshape(img, (-1,)))
        X_features.append(feature)
    list_feature.append(X_features)
    
X_all_reduced = np.concatenate(list_feature,axis=1)

X_train_reduced = X_all_reduced[:49000]
X_test_reduced = X_all_reduced[49000:59000]
X_val_reduced = X_all_reduced[59000:]

[ 1.63753366  0.44205163 -0.38837802] 
 [[-0.38325935 -0.45392524  0.63634845]
 [-0.29962773 -0.09836743 -0.75243352]
 [-0.87369073  0.88559343  0.17001305]]


In [43]:
a = np.array([[1,9,3,6], [5,6,13,78], [9,10,11,69]])
b = np.array([[1,9,3,6], [5,6,13,78], [9,10,11,69]])
c = np.array([[1,9,3,6], [5,6,13,78], [9,10,11,69]])
X_all = np.concatenate([a,b,c],axis=1)
print(X_all)


[[ 1  9  3  6  1  9  3  6  1  9  3  6]
 [ 5  6 13 78  5  6 13 78  5  6 13 78]
 [ 9 10 11 69  9 10 11 69  9 10 11 69]]


In [44]:
img = np.array([1,9,3,6]) 
np.reshape(img, (-1,))

array([1, 9, 3, 6])